[build]
  command = "sed -i \"s|onboarding_login|${onboarding_login}|g\" netlify.toml && npm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  
[[headers]]
  for = "/onboarding"
   [headers.values]
    Basic-Auth = "onboarding_login"