
[build]
  command = "sed -i s/ONBOARDING_LOGIN/$admin:Lemonade97989@/g netlify.toml && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  
[[headers]]
  for = "/onboarding"
   [headers.values]
    Basic-Auth = "ONBOARDING_LOGIN"