[build]
    command = "yarn run build"
    publish = "/build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        test-it = "true"
        cache-control = "no-cache"